### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by polyglotte** [skiselev/diy-prusa-i3-mk3-bear#2]
Hi, I was checking some stl links for building this printer and some of them are broken, could you upload them again?

**Comment by skiselev** [comment]
Can you please point out which links specifically?
Also note that Prusa/Bear project is constantly updating. So please follow the Bear project instructions. My instructions are more of the recommendations for building a printer from scratch vs. purchasing Prusa MK3S and upgrading it.

**Comment by polyglotte** [comment]
the X axis and carriage links, thank's
I'm also making one from scratch, I don't even own a 3d printer yet, looking for a nice Fablab/Hackerspace/hearted person to print my parts.
