### ISSUE TITLE
LCD not working?

### ISSUE THREAD

**Issue by Schmools** [skiselev/diy-prusa-i3-mk3-bear#3]
Hi, thanks for the great documentation of your build. I've followed what you did and have 95% of everything assembled, however my LCD doesn't turn on at all, though if I mess with the knob the backlight sometimes flickers and the piezo beeps. Was wondering if you experienced anything similiar in your build process, and if that was the case how you remedied that. Thanks again for the great documentation!

**Comment by elpeter25** [comment]
Just in case... did you try to switch the LCD cable? that works on other printers with non standard LCDs

**Comment by Schmools** [comment]
Yeah, messed with it for a day or so and it turns out if you just buy one of the reprap displays arbitrarily, you have to be careful because the cables defaultly can come backwards, so you need to file down the tabs on the connectors to install them backwards.

**Comment by elpeter25** [comment]
Actually you can just take out the plastic from the pcb with a pair of pliers and mount it back reverted.
